// js/dom.js
export const dom = {
    form: document.getElementById('prompt-form'),
    allTextareas: document.querySelectorAll('textarea'),
    promptParts: document.querySelectorAll('.prompt-part'),
    savableFields: document.querySelectorAll('.savable-field'),
    positiveOutput: document.getElementById('output-positive'),
    negativeOutput: document.getElementById('output-negative'),
    rebuildBtn: document.getElementById('rebuild-prompt'),
    presetNameInput: document.getElementById('preset-name'),
    presetSelect: document.getElementById('preset-select'),
    savePresetBtn: document.getElementById('save-preset-btn'),
    deletePresetBtn: document.getElementById('delete-preset-btn'),
    presetPreview: document.getElementById('preset-preview'),
    showManualBtn: document.getElementById('show-manual-btn'),
    manualModal: document.getElementById('manual-modal'),
    closeManualBtn: document.getElementById('close-manual-btn'),
    manualBody: document.querySelector('.manual-body'),
    langToggleCheckbox: document.getElementById('lang-toggle-checkbox'),
    themeToggleCheckbox: document.getElementById('theme-toggle-checkbox'),
    importPresetsBtn: document.getElementById('import-presets-btn'),
    exportPresetsBtn: document.getElementById('export-presets-btn'),
    appTitle: document.getElementById('app-title'),
    copyPositiveBtn: document.getElementById('copy-positive'),
    copyNegativeBtn: document.getElementById('copy-negative'),
    clearFormBtn: document.getElementById('clear-form-btn'),
    tagBrowserModal: document.getElementById('tag-browser-modal'),
    closeTagBrowserBtn: document.getElementById('close-tag-browser-btn'),
    tagBrowserTitle: document.getElementById('tag-browser-title'),
    tagBrowserSubcategories: document.getElementById('tag-browser-subcategories'),
    tagBrowserSearch: document.getElementById('tag-browser-search'),
    tagBrowserSelectionPreview: document.getElementById('tag-browser-selection-preview'),
    addSelectedTagsBtn: document.getElementById('add-selected-tags-btn'),
    resetSelectedTagsBtn: document.getElementById('reset-selected-tags-btn'),
    // ЭЛЕМЕНТ, КОТОРОГО НЕ ХВАТАЛО
    historyList: document.getElementById('history-list')
};